version: '3'
services:
  psi_nginx:
    container_name: psi_nginx
    image: nginx
    ports:
        - "80:80" 
        - "443:443" 
    volumes:
      - ../public:/usr/share/nginx/html/
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    tty: true
